"""
CodeInterpreter tool - Execute Python code in a stateful Jupyter kernel.
Simplified version adapted from the WebWatcher implementation.
"""

import asyncio
import ast
import atexit
import base64
import concurrent.futures
import io
import json
import os
import queue
import re
import signal
import subprocess
import sys
import threading
import time
import uuid
from typing import Dict

from PIL import Image
from tools.base import BaseTool
from tools.tool_registry import register_tool

# Check dependencies
try:
    from jupyter_client import BlockingKernelClient
    import PIL.Image
    JUPYTER_AVAILABLE = True
except ImportError:
    JUPYTER_AVAILABLE = False
    print("Warning: jupyter-client or pillow not installed. Install with: pip install jupyter-client pillow")

_KERNEL_CLIENTS: dict = {}
_MISC_SUBPROCESSES: Dict[str, subprocess.Popen] = {}
_KERNEL_LOCK = threading.Lock()

LAUNCH_KERNEL_PY = """
from ipykernel import kernelapp as app
app.launch_new_instance()
"""


def _kill_kernels_and_subprocesses(_sig_num=None, _frame=None):
    """Clean up all kernels and subprocesses."""
    with _KERNEL_LOCK:
        for v in list(_KERNEL_CLIENTS.values()):
            try:
                v.shutdown()
            except:
                pass
        _KERNEL_CLIENTS.clear()

        for v in list(_MISC_SUBPROCESSES.values()):
            try:
                v.terminate()
            except:
                pass
        _MISC_SUBPROCESSES.clear()


# Register cleanup handler
if threading.current_thread() is threading.main_thread():
    atexit.register(_kill_kernels_and_subprocesses)


def execute_with_timeout(func, timeout, **kwargs):
    """Execute a function within a timeout, supporting graceful interruption."""
    import time as time_module
    import threading
    start_time = time_module.time()

    stop_event = threading.Event()
    kwargs['_stop_event'] = stop_event

    with concurrent.futures.ThreadPoolExecutor() as executor:
        future = executor.submit(func, **kwargs)
        try:
            result = future.result(timeout=timeout)
            elapsed = time_module.time() - start_time
            print(f"[CodeInterpreter] execute_with_timeout completed in {elapsed:.2f}s (timeout was {timeout}s)")
            return result
        except concurrent.futures.TimeoutError:
            stop_event.set()
            future.cancel()
            elapsed = time_module.time() - start_time
            print(f"[CodeInterpreter] Execution timeout after {elapsed:.2f}s (limit: {timeout}s), stop event set")
            return f'TimeoutError: Function execution timed out after {timeout} seconds.'
        except Exception as e:
            stop_event.set()
            elapsed = time_module.time() - start_time
            print(f"[CodeInterpreter] execute_with_timeout exception after {elapsed:.2f}s: {e}")
            return f'Fatal Error: {e}'


@register_tool('code_interpreter')
class CodeInterpreter(BaseTool):
    name = 'code_interpreter'
    description = '''
Executes Python code in a stateful Jupyter kernel and return results.

Capabilities:
- Use PIL, NumPy, or OpenCV to process or analyze images to improve understanding.
- Perform complex mathematical calculations or data manipulation.
- Code execution is persistent: variables and functions are stored and reusable in subsequent calls.

Image Variables (Pre-loaded as PIL Image objects):
- original_image / original_image_N (N=1,2,3,...): The original input images are already loaded as PIL Image objects. The following code is automatically executed before your code:
  ```python
  from PIL import Image
  original_image = Image.open('...')
  original_image_1 = Image.open('...')  # if multiple images exist
  ```
  You can directly use these variables (e.g., `original_image`, `original_image_1`) without loading them again.
- tool_image_N (N=1,2,3,...): Images generated by your previous code calls.
- observation_N (N=1,2,3,...): Images generated by zoom tool operations.

Visualization & Output:
- To view generated images, return the object, use plt.show(), or save it (e.g., image.save('out.png')). 
- DO NOT use image.show(). 
- Displayed images will be available as "tool_image_N" in the next turn.

Pre-installed packages:
- PIL
- NumPy
- OpenCV
- Matplotlib
- SciPy
- Scikit-learn
- Scikit-image
- Pandas
- SymPy
'''
    parameters = {
        "type": "object",
        "properties": {
            "code": {
                "type": "string",
                "description": "Python code to execute in the Jupyter kernel"
            }
        },
        "required": ["code"]
    }

    def __init__(self, config=None):
        super().__init__(config)
        if not JUPYTER_AVAILABLE:
            raise ImportError("jupyter-client and pillow are required for CodeInterpreter")

        self.instance_id = str(uuid.uuid4())

        # Set up per-instance work directory to avoid file conflicts in parallel execution
        if config and 'work_dir' in config:
            base_dir = config['work_dir']
            self.work_dir = os.path.join(base_dir, self.instance_id)
        else:
            default_base_dir = '/tmp/code_interpreter'
            self.work_dir = os.path.join(default_base_dir, self.instance_id)

        os.makedirs(self.work_dir, exist_ok=True)

        # Output-detection timeout: if no valid output is received for this duration, consider it hung
        self.output_timeout = config.get('output_timeout', 30) if config else 30
        if self.output_timeout is None or self.output_timeout == 0:
            self.output_timeout = None
            raise ValueError("output_timeout must be set and > 0. It is required for timeout detection.")

    def _clean_work_dir(self, input_image_files=None):
        """
        Clean up input image files from the work directory while preserving user-saved files.

        Strategy:
        1. Keep kernel-related files (kernel_connection_file_*, launch_kernel_*)
        2. Only delete input images (from image_map; they will be re-injected)
        3. Preserve user-saved image files (for cross-step access)
        4. Delete other generated files (.py, .txt, .csv, etc.) except kernel files
        """
        if not os.path.exists(self.work_dir):
            return

        input_files = set()
        if input_image_files:
            input_files = input_image_files

        try:
            for f in os.listdir(self.work_dir):
                file_path = os.path.join(self.work_dir, f)

                if f.startswith('kernel_connection_file_') or f.startswith('launch_kernel_'):
                    continue

                if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                    if f in input_files:
                        try:
                            os.remove(file_path)
                        except OSError:
                            pass

                if f.endswith(('.py', '.txt', '.csv', '.json')) and not f.startswith('kernel_'):
                    if 'kernel' not in f.lower() and 'connection' not in f.lower():
                        try:
                            os.remove(file_path)
                        except OSError:
                            pass
        except Exception as e:
            print(f"[CodeInterpreter] Warning: Failed to clean work_dir: {e}")

    def call(self, params, image_map: Dict[str, Image.Image] = None, **kwargs):
        """
        Execute Python code, optionally processing provided images.

        Args:
            params: Dictionary containing 'code' or a raw code string.
            image_map: Mapping of image identifiers to PIL Image objects.
            **kwargs: Additional keyword arguments.

        Returns:
            Code execution result string.
        """
        if isinstance(params, str):
            try:
                params = json.loads(params)
            except json.JSONDecodeError:
                code = params
        else:
            code = params.get('code', '')

        # Extract code from markdown code blocks if present
        triple_match = re.search(r'```[^\n]*\n(.+?)```', code, re.DOTALL)
        if triple_match:
            code = triple_match.group(1)

        if not code.strip():
            return 'Error: No code provided'

        # Record input image filenames for cleanup
        image_extensions = ['.png', '.jpg', '.jpeg', '.gif', '.bmp']
        input_image_files = set()
        if image_map:
            for name in image_map.keys():
                var_name = re.sub(r'[^a-zA-Z0-9_]', '', name)
                if var_name:
                    for ext in image_extensions:
                        input_image_files.add(f'{var_name}{ext}')
                if name == 'original_image' or name.startswith('original_image_'):
                    for ext in image_extensions:
                        input_image_files.add(f'image{ext}')

        self._clean_work_dir(input_image_files)

        # Count existing tool_image_* entries for naming new images
        tool_image_count = 0
        if image_map:
            tool_image_count = len([k for k in image_map.keys() if k.startswith('tool_image_')])

        # Prepare image loading code to inject before user code
        image_load_code = ''
        if image_map:
            image_load_code += 'from PIL import Image\n'
            sorted_image_items = sorted(image_map.items(), key=lambda x: (
                0 if x[0] == 'original_image' else (1 if x[0].startswith('original_image_') else 2),
                x[0]
            ))

            for name, img in sorted_image_items:
                var_name = re.sub(r'[^a-zA-Z0-9_]', '', name)
                if not var_name:
                    continue

                file_path = os.path.join(self.work_dir, f'{var_name}.png')
                img.save(file_path)
                image_load_code += f"{var_name} = Image.open('{file_path}')\n"

            # Create image.png alias and `image` variable for backward compatibility
            if 'original_image' in image_map:
                image_alias_path = os.path.join(self.work_dir, 'image.png')
                image_map['original_image'].save(image_alias_path)
                image_load_code += "image = original_image\n"

        # Optional: convert normalized bbox coordinates to pixel coordinates
        if os.environ.get('ENABLE_BBOX_CLEANING', 'false').lower() == 'true':
            cleaned_code = self._clean_bbox_coordinates(code, image_map)
        else:
            cleaned_code = code

        full_code = image_load_code + cleaned_code

        if 'exit' in cleaned_code.lower():
            return 'Error: Using exit() is not allowed'

        try:
            ast.parse(cleaned_code)
        except SyntaxError as e:
            return f'SyntaxError: {e}'

        # Record files present before execution to detect newly generated images
        existing_image_files = set()
        if os.path.exists(self.work_dir):
            for f in os.listdir(self.work_dir):
                if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                    if f.startswith('kernel_') or f.startswith('launch_kernel_'):
                        continue
                    existing_image_files.add(f)

        print(f"[CodeInterpreter] Executing code:\n{full_code[:300]}...")

        try:
            # Get or create kernel (thread-isolated for parallel execution)
            import threading
            thread_id = threading.get_ident()
            kernel_id = f'{self.instance_id}_{os.getpid()}_{thread_id}'

            # Double-checked locking to protect global dict access
            kc = None
            with _KERNEL_LOCK:
                if kernel_id in _KERNEL_CLIENTS:
                    kc = _KERNEL_CLIENTS[kernel_id]

            # Start kernel outside the lock to avoid blocking other threads
            if kc is None:
                try:
                    new_kc, new_subproc = self._start_kernel(kernel_id)
                except Exception as e:
                    print(f"[CodeInterpreter] ERROR - Failed to start kernel {kernel_id}: {e}")
                    import traceback
                    traceback.print_exc()
                    raise

                with _KERNEL_LOCK:
                    if kernel_id not in _KERNEL_CLIENTS:
                        _KERNEL_CLIENTS[kernel_id] = new_kc
                        _MISC_SUBPROCESSES[kernel_id] = new_subproc
                        kc = new_kc
                    else:
                        kc = _KERNEL_CLIENTS[kernel_id]
                        try:
                            new_kc.shutdown()
                            new_subproc.terminate()
                        except Exception:
                            pass

            full_code += '\n\n'

            # Use 2x output_timeout as a fallback ceiling for execute_with_timeout
            if self.output_timeout is None or self.output_timeout <= 0:
                raise ValueError("output_timeout must be set and > 0. It is required for timeout detection.")
            execution_timeout = self.output_timeout * 2

            result = execute_with_timeout(
                self._execute_code,
                execution_timeout,
                kc=kc,
                code=full_code,
                existing_image_files=existing_image_files,
                kernel_id=kernel_id,
                tool_image_start_count=tool_image_count
            )

            print(f"[CodeInterpreter] Execution completed")
            return result if result.strip() else 'Finished execution.'

        except Exception as e:
            error_msg = f"Error executing code: {str(e)}"
            print(f"[CodeInterpreter] {error_msg}")
            return error_msg

    def _clean_bbox_coordinates(self, code: str, image_map: dict) -> str:
        """
        Convert normalized bbox coordinates (0-999) in user code to pixel coordinates.

        Supported patterns:
        1. image.crop((x1, y1, x2, y2))
        2. image.paste(..., (x1, y1, x2, y2))
        3. ImageDraw.rectangle((x1, y1, x2, y2))
        4. Other drawing operations (ellipse, text, etc.)
        5. Variable assignment: bbox = (x1, y1, x2, y2) or [x1, y1, x2, y2]
        6. Function calls: func((x1, y1, x2, y2))

        Detection rule: four consecutive integers in [0, 1000] on an image larger
        than 1000 pixels are treated as normalized coordinates and converted.
        """
        if not image_map:
            return code

        main_image = image_map.get('original_image')
        if not main_image:
            return code

        img_width, img_height = main_image.size

        import re

        def convert_coords(x1, y1, x2, y2):
            """Convert coordinates and return whether conversion was applied."""
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)

            is_normalized = (
                0 <= x1 <= 1000 and 0 <= y1 <= 1000 and
                0 <= x2 <= 1000 and 0 <= y2 <= 1000 and
                x1 < x2 and y1 < y2
            )

            if is_normalized:
                px1 = int(x1 * img_width / 1000)
                py1 = int(y1 * img_height / 1000)
                px2 = int(x2 * img_width / 1000)
                py2 = int(y2 * img_height / 1000)

                print(f"[BBox Clean] Converted normalized [{x1}, {y1}, {x2}, {y2}] -> pixel [{px1}, {py1}, {px2}, {py2}]")
                return (px1, py1, px2, py2), True
            else:
                return (x1, y1, x2, y2), False

        cleaned_code = code

        # Pattern 1: variable assignment - left, top, right, bottom = 850, 0, 1000, 300
        assignment_pattern = r'(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*=\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)'
        def replace_assignment(match):
            var1, var2, var3, var4 = match.groups()[:4]
            x1, y1, x2, y2 = match.groups()[4:]
            coords, converted = convert_coords(x1, y1, x2, y2)
            if converted:
                px1, py1, px2, py2 = coords
                return f"{var1}, {var2}, {var3}, {var4} = {px1}, {py1}, {px2}, {py2}"
            return match.group(0)

        cleaned_code = re.sub(assignment_pattern, replace_assignment, cleaned_code)

        # Pattern 2: tuple format - (x1, y1, x2, y2)
        tuple_pattern = r'\((\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\)'
        def replace_tuple(match):
            x1, y1, x2, y2 = match.groups()
            coords, converted = convert_coords(x1, y1, x2, y2)
            if converted:
                px1, py1, px2, py2 = coords
                return f"({px1}, {py1}, {px2}, {py2})"
            return match.group(0)

        cleaned_code = re.sub(tuple_pattern, replace_tuple, cleaned_code)

        # Pattern 3: list format - [x1, y1, x2, y2]
        list_pattern = r'\[(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\]'
        def replace_list(match):
            x1, y1, x2, y2 = match.groups()
            coords, converted = convert_coords(x1, y1, x2, y2)
            if converted:
                px1, py1, px2, py2 = coords
                return f"[{px1}, {py1}, {px2}, {py2}]"
            return match.group(0)

        cleaned_code = re.sub(list_pattern, replace_list, cleaned_code)

        return cleaned_code

    def _start_kernel(self, kernel_id: str):
        """Start a Jupyter kernel and return (client, process)."""
        connection_file = os.path.join(self.work_dir, f'kernel_connection_file_{kernel_id}.json')
        launch_kernel_script = os.path.join(self.work_dir, f'launch_kernel_{kernel_id}.py')

        for f in [connection_file, launch_kernel_script]:
            if os.path.exists(f):
                os.remove(f)

        with open(launch_kernel_script, 'w') as fout:
            fout.write(LAUNCH_KERNEL_PY)

        # Suppress stderr to avoid ZMQ async callback errors polluting logs
        try:
            kernel_process = subprocess.Popen(
                [
                    sys.executable,
                    os.path.abspath(launch_kernel_script),
                    '--IPKernelApp.connection_file',
                    os.path.abspath(connection_file),
                    '--matplotlib=inline',
                    '--quiet',
                ],
                cwd=os.path.abspath(self.work_dir),
                stderr=subprocess.DEVNULL,
            )
        except Exception as e:
            print(f"[CodeInterpreter] ERROR - Failed to start kernel process: {e}")
            raise

        # Wait for connection file to be created
        max_wait = 10
        wait_time = 0
        while not os.path.isfile(connection_file) and wait_time < max_wait:
            time.sleep(0.1)
            wait_time += 0.1

        if not os.path.isfile(connection_file):
            error_msg = f"Kernel connection file not created after {max_wait}s"
            print(f"[CodeInterpreter] ERROR - {error_msg}")
            try:
                kernel_process.terminate()
            except:
                pass
            raise RuntimeError(error_msg)

        # Wait for file to be readable
        while wait_time < max_wait:
            try:
                with open(connection_file, 'r') as fp:
                    json.load(fp)
                break
            except (json.JSONDecodeError, IOError) as e:
                time.sleep(0.1)
                wait_time += 0.1
                if wait_time >= max_wait:
                    error_msg = f"Connection file not readable after {max_wait}s: {e}"
                    print(f"[CodeInterpreter] ERROR - {error_msg}")
                    try:
                        kernel_process.terminate()
                    except:
                        pass
                    raise RuntimeError(error_msg)

        try:
            kc = BlockingKernelClient(connection_file=connection_file)
        except Exception as e:
            print(f"[CodeInterpreter] ERROR - Failed to create BlockingKernelClient: {e}")
            try:
                kernel_process.terminate()
            except:
                pass
            raise

        try:
            asyncio.set_event_loop_policy(AnyThreadEventLoopPolicy())
        except Exception:
            pass

        try:
            kc.load_connection_file()
            kc.start_channels()
            kc.wait_for_ready()
        except Exception as e:
            print(f"[CodeInterpreter] ERROR - Failed to initialize kernel client: {e}")
            import traceback
            traceback.print_exc()
            try:
                kc.shutdown()
                kernel_process.terminate()
            except:
                pass
            raise

        return kc, kernel_process

    def _init_kernel_timeout(self, kc):
        """Initialize the kernel timeout mechanism (register signal handler)."""
        init_code = """
import signal
import sys

try:
    import matplotlib
except ImportError:
    pass

def _m6_timeout_handler(_signum=None, _frame=None):
    raise TimeoutError('M6_CODE_INTERPRETER_TIMEOUT')

try:
    signal.signal(signal.SIGALRM, _m6_timeout_handler)
except AttributeError:  # Windows does not support SIGALRM
    pass

class _M6CountdownTimer:
    @classmethod
    def start(cls, timeout: int):
        try:
            signal.alarm(timeout)
        except AttributeError:
            pass
    
    @classmethod
    def cancel(cls):
        try:
            signal.alarm(0)
        except AttributeError:
            pass
"""
        try:
            kc.wait_for_ready()
            kc.execute(init_code)
            time.sleep(0.1)
        except Exception as e:
            print(f"[CodeInterpreter] Warning: Failed to initialize timeout mechanism: {e}")

    def _is_valid_output(self, msg_type: str, msg: dict) -> bool:
        """Check whether a kernel message counts as valid output for timeout detection."""
        if msg_type == 'status':
            return False
        elif msg_type == 'execute_result':
            data = msg.get('content', {}).get('data', {})
            if 'image/png' in data:
                return True
            text = data.get('text/plain', '')
            return bool(text and text.strip())
        elif msg_type == 'display_data':
            data = msg.get('content', {}).get('data', {})
            if 'image/png' in data:
                return True
            text = data.get('text/plain', '')
            return bool(text and text.strip())
        elif msg_type == 'stream':
            text = msg.get('content', {}).get('text', '')
            return bool(text and text.strip())
        elif msg_type == 'error':
            return True
        return False

    def _interrupt_kernel(self, kernel_id, kc):
        """
        Interrupt a running kernel.

        Attempts in order:
        1. client.interrupt() or shell_channel.send_interrupt()
        2. Send SIGINT to the kernel process
        3. If all fail, log that the kernel may need a restart
        """
        if kernel_id is None:
            print(f"[CodeInterpreter] Cannot interrupt kernel: kernel_id is None")
            return

        try:
            if hasattr(kc, 'interrupt'):
                kc.interrupt()
                print(f"[CodeInterpreter] Kernel interrupt via interrupt() method")
                return
            elif hasattr(kc, 'shell_channel'):
                kc.shell_channel.send_interrupt()
                print(f"[CodeInterpreter] Kernel interrupt via shell_channel.send_interrupt()")
                return
        except Exception as e:
            print(f"[CodeInterpreter] Failed to interrupt kernel via client: {e}")

        try:
            with _KERNEL_LOCK:
                if kernel_id in _MISC_SUBPROCESSES:
                    kernel_process = _MISC_SUBPROCESSES[kernel_id]
                    if kernel_process and kernel_process.poll() is None:
                        kernel_process.send_signal(signal.SIGINT)
                        print(f"[CodeInterpreter] Kernel interrupt via SIGINT signal sent to process")
                        time.sleep(0.5)
                        if kernel_process.poll() is None:
                            print(f"[CodeInterpreter] Kernel process still running, may need restart")
                        return
        except Exception as e:
            print(f"[CodeInterpreter] Failed to interrupt kernel via signal: {e}")

        print(f"[CodeInterpreter] All interrupt methods failed, kernel may need restart on next call")

    def _execute_code(self, kc, code: str, existing_image_files=None, _stop_event=None, kernel_id=None, tool_image_start_count=0) -> str:
        """
        Execute code and collect results.

        Args:
            kc: Kernel client.
            code: Code to execute.
            existing_image_files: Set of image files present before execution.
            _stop_event: threading.Event for graceful interruption.
            kernel_id: Kernel ID for process-level interrupt.
            tool_image_start_count: Current tool_image_* count for naming.
        """
        if existing_image_files is None:
            existing_image_files = set()
            if os.path.exists(self.work_dir):
                for f in os.listdir(self.work_dir):
                    if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                        if f.startswith('kernel_') or f.startswith('launch_kernel_'):
                            continue
                        existing_image_files.add(f)

        served_images = set()

        try:
            kc.wait_for_ready()
        except Exception as e:
            return f'Fatal Error: Kernel is not ready. {str(e)}'

        try:
            kc.execute(code)
        except Exception as e:
            return f'Fatal Error: Failed to execute code. {str(e)}'

        result = ''
        image_idx = 0
        tool_image_counter = tool_image_start_count
        start_time = time.time()

        last_output_time = start_time
        output_timeout_enabled = self.output_timeout is not None and self.output_timeout > 0

        if not output_timeout_enabled:
            raise ValueError("output_timeout must be set and > 0. It is required for timeout detection.")

        while True:
            text = ''
            image = ''
            finished = False
            msg_type = 'error'

            # Unified checkpoint: check for timeout and interruption
            if _stop_event and _stop_event.is_set():
                text = 'TimeoutError: Execution was interrupted due to timeout.'
                print(f"[CodeInterpreter] Stop event detected, interrupting execution")
                self._interrupt_kernel(kernel_id, kc)
                if text:
                    result += f'\n\nerror:\n\n```\n{text}\n```'
                finished = True
                break

            time_since_last_output = time.time() - last_output_time

            if time_since_last_output >= self.output_timeout:
                text = f'TimeoutError: No output received for {time_since_last_output:.1f} seconds (output_timeout: {self.output_timeout}s). The kernel may be unresponsive or stuck.'
                print(f"[CodeInterpreter] Output timeout detected: {time_since_last_output:.1f}s without valid output")
                self._interrupt_kernel(kernel_id, kc)
                if text:
                    result += f'\n\nerror:\n\n```\n{text}\n```'
                finished = True
                break

            try:
                time_until_output_timeout = self.output_timeout - time_since_last_output
                single_wait_timeout = min(max(1, time_until_output_timeout), 10)

                if _stop_event and _stop_event.is_set():
                    continue

                msg = kc.get_iopub_msg(timeout=single_wait_timeout)
                msg_type = msg.get('msg_type', 'unknown')

                if output_timeout_enabled and self._is_valid_output(msg_type, msg):
                    last_output_time = time.time()
                    print(f"[CodeInterpreter] Received valid output (type: {msg_type}), resetting output timeout timer")

                if msg_type == 'status':
                    execution_state = msg.get('content', {}).get('execution_state', 'unknown')
                    if execution_state == 'idle':
                        finished = True

                elif msg_type == 'execute_result':
                    text = msg.get('content', {}).get('data', {}).get('text/plain', '')
                    if 'image/png' in msg.get('content', {}).get('data', {}):
                        image_b64 = msg['content']['data']['image/png']
                        image_url = self._serve_image(image_b64)
                        if os.path.isfile(image_url):
                            served_images.add(os.path.basename(image_url))
                        tool_image_counter += 1
                        image = f'![tool_image_{tool_image_counter}]({image_url})'

                elif msg_type == 'display_data':
                    if 'image/png' in msg.get('content', {}).get('data', {}):
                        image_b64 = msg['content']['data']['image/png']
                        image_url = self._serve_image(image_b64)
                        if os.path.isfile(image_url):
                            served_images.add(os.path.basename(image_url))
                        tool_image_counter += 1
                        image = f'![tool_image_{tool_image_counter}]({image_url})'
                    else:
                        text = msg.get('content', {}).get('data', {}).get('text/plain', '')

                elif msg_type == 'stream':
                    msg_type = msg.get('content', {}).get('name', 'stdout')
                    text = msg.get('content', {}).get('text', '')

                elif msg_type == 'error':
                    traceback_list = msg.get('content', {}).get('traceback', [])
                    error_text = _escape_ansi('\n'.join(traceback_list))
                    text = error_text

            except queue.Empty:
                continue

            except (ValueError, ConnectionError, OSError) as e:
                error_msg = str(e)
                if result.strip():
                    finished = True
                else:
                    text = f'Error: {error_msg}. Kernel communication may be interrupted.'
                    finished = True

            except BaseException as e:
                error_msg = str(e)
                error_type = type(e).__name__
                print(f"[CodeInterpreter] FATAL - {error_type}: {error_msg}")
                import traceback
                traceback.print_exc()

                text = f'Fatal Error ({error_type}): {error_msg}. The code interpreter encountered an unexpected error.'
                finished = True

            if text:
                result += f'\n\n{msg_type}:\n\n```\n{text}\n```'
            if image:
                result += f'\n\n{image}'
            if finished:
                break

        is_output_timeout = output_timeout_enabled and result and "No output received" in result

        if is_output_timeout:
            print(f"[CodeInterpreter] Skipping image scan due to output timeout, returning immediately")
            return result.lstrip('\n')

        # Scan for newly generated image files after execution
        new_image_files = []
        if os.path.exists(self.work_dir):
            for f in os.listdir(self.work_dir):
                if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                    if f.startswith('kernel_') or f.startswith('launch_kernel_'):
                        continue
                    if f in served_images:
                        continue
                    if f not in existing_image_files:
                        new_image_files.append(f)

        for img_file in sorted(new_image_files):
            image_path = os.path.join(self.work_dir, img_file)
            if os.path.exists(image_path):
                tool_image_counter += 1
                abs_image_path = os.path.abspath(image_path)
                result += f'\n\n![tool_image_{tool_image_counter}]({abs_image_path})'
                print(f"[CodeInterpreter] Auto-detected saved image: {img_file} -> {abs_image_path}")

        return result.lstrip('\n')

    def _serve_image(self, image_base64: str) -> str:
        """Save a base64-encoded image and return its file path."""
        image_file = f'{uuid.uuid4()}.png'
        local_image_file = os.path.join(self.work_dir, image_file)

        png_bytes = base64.b64decode(image_base64)
        bytes_io = io.BytesIO(png_bytes)
        PIL.Image.open(bytes_io).save(local_image_file, 'png')

        return local_image_file

    def __del__(self):
        """Clean up resources."""
        try:
            import threading
            thread_id = threading.get_ident()
            kernel_id = f'{self.instance_id}_{os.getpid()}_{thread_id}'

            with _KERNEL_LOCK:
                if kernel_id in _KERNEL_CLIENTS:
                    try:
                        _KERNEL_CLIENTS[kernel_id].shutdown()
                    except:
                        pass
                    del _KERNEL_CLIENTS[kernel_id]
                if kernel_id in _MISC_SUBPROCESSES:
                    try:
                        _MISC_SUBPROCESSES[kernel_id].terminate()
                    except:
                        pass
                    del _MISC_SUBPROCESSES[kernel_id]
        except:
            pass


def _escape_ansi(line: str) -> str:
    """Remove ANSI escape sequences."""
    ansi_escape = re.compile(r'(?:\x1B[@-_]|[\x80-\x9F])[0-?]*[ -/]*[@-~]')
    return ansi_escape.sub('', line)


# Event loop policy for compatibility
if sys.platform == 'win32' and hasattr(asyncio, 'WindowsSelectorEventLoopPolicy'):
    _BasePolicy = asyncio.WindowsSelectorEventLoopPolicy
else:
    _BasePolicy = asyncio.DefaultEventLoopPolicy


class AnyThreadEventLoopPolicy(_BasePolicy):
    """Event loop policy that allows creating event loops on any thread."""

    def get_event_loop(self) -> asyncio.AbstractEventLoop:
        try:
            return super().get_event_loop()
        except RuntimeError:
            loop = self.new_event_loop()
            self.set_event_loop(loop)
            return loop
